---
title: "ARM"
output: pdf_document
date: '2022-09-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import required libraries
library(arules)
library(arulesViz)
```


```{r}
# read the text data as transactions
trans <- read.transactions("C:/Users/sirid/OneDrive/Documents/ML/transaction_data.csv", format = "basket", cols = NULL, sep = ",")
```

```{r}
# calculate apriori, here I chose these values because the number of rules generated were close to 50
rules <- arules::apriori(trans, parameter = list(support = 0.025, confidence = 0.75, minlen = 2))
inspect(rules)
```

```{r}
# sort the rules by support
sort_rules <- sort(rules, by = "support", decreasing = TRUE)
inspect(sort_rules[1:30])
```

```{r}
# sort the rules by confidence
sort_rules <- sort(rules, by = "confidence", decreasing = TRUE)
inspect(sort_rules[1:15])
```

```{r}
#sort the rules by lift
sort_rules <- sort(rules, by = "lift", decreasing = TRUE)
inspect(sort_rules[1:15])
```

```{r}
#plot the top 15 rules. 
plot(sort(rules, by = "support", decreasing = TRUE), method = "graph", limit = 15)
```

```{r}
plot(sort_rules, method="graph", engine="htmlwidget", limit = 15)
```

```{r}
plot(sort(rules, by = "confidence", decreasing = TRUE), method="graph", engine="interactive", limit = 15)
```


```{r}
num_data <- read.csv(file = "C:/Users/sirid/OneDrive/Documents/ML/data_num.csv")
tot_data <- read.csv(file = "C:/Users/sirid/OneDrive/Documents/ML/data.csv")
```

```{r}
#scale the data for k means
scaled_data <- scale(num_data[,2:16])
km <- kmeans(scaled_data, centers = 4, nstart = 25)
```


```{r}
library(factoextra)
# visualize the clusters
factoextra::fviz_cluster(km, data = scaled_data,
              geom = "point",
              ellipse.type = "convex"
 )
```

```{r}
library(dplyr)
rooms <- matrix(c(num_data$room_type, km$cluster), ncol = 2, byrow = FALSE)
rooms <- as.data.frame(rooms)
colnames(rooms)<- c('room_type', 'cluster')
rooms %>% count(room_type, cluster)
```

```{r}
# sample the data to get a sample
scaled_data_sample <- scale(num_data[seq(331,450,by = 10),2:16])
sam <- as.data.frame(scaled_data_sample)
# calculate the distance matrices with three different distance metrics
dist_mat_e <- dist(sam, method="euclidean")
dist_mat_m <- dist(sam, method="manhattan")
dist_mat_c <- dist(sam, method="minkowski", p = 3)
```

```{r}
# get the hierarchial clusters with all the distance matrices
groups_E <- hclust(dist_mat_e,method="ward.D")
plot(groups_E, cex=0.9, hang=-1, main = "Euclidean")
rect.hclust(groups_E, k=4)

groups_M <- hclust(dist_mat_m,method="ward.D")
plot(groups_M, cex=.7, hang=-30,main = "manhattan")
rect.hclust(groups_M, k=4)

groups_C <- hclust(dist_mat_c,method="ward.D")
plot(groups_C, cex=0.9, hang=-1, main = "minkowski, p = 3")
rect.hclust(groups_C, k=4)
```
```{r}
tot_data[seq(331,450,by = 10),]
```
```{r}
# to find the optimal number for epsilon and minimum points
# k is minimum points -1
# Minimum points is the 2*features
library(dbscan)
kNNdistplot(scaled_data, k = 29)
```


```{r}
library(fpc)
set.seed(220)  # Setting seed
# call dbscan by giving scaled data as an input
Dbscan_cl <- dbscan(scaled_data, eps = 5, MinPts = 30)
Dbscan_cl
```

```{r}
# visualise the clusters
factoextra::fviz_cluster(Dbscan_cl, data = scaled_data,
              geom = "point",
              ellipse.type = "confidence"
 )
```


References 
https://towardsdatascience.com/how-to-export-pandas-dataframe-to-csv-2038e43d9c03
https://blog.aptitive.com/building-the-transactions-class-for-association-rule-mining-in-r-using-arules-and-apriori-c6be64268bc4
https://www.rdocumentation.org/packages/arulesViz/versions/1.5-0
https://www.askpython.com/python/examples/plot-k-means-clusters-python
https://www.geeksforgeeks.org/dbscan-clustering-in-r-programming/#:~:text=Density%2DBased%20Clustering%20of%20Applications,density%20reachability%20and%20density%20connectivity.
https://rdrr.io/cran/dbscan/man/kNNdist.html




